name: Update Google Calendar

on:
  schedule:
    - cron: '0 12 * * 3'  # Ejecutar todos los miércoles a las 12:00 UTC
  workflow_dispatch:  # Permitir la ejecución manual

jobs:
  update-calendar:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.4'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip xvfb libxi6 libgconf-2-4
        wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo dpkg -i google-chrome-stable_current_amd64.deb
        sudo apt-get -fy install
        CHROME_DRIVER_VERSION=`curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE`
        wget -q https://chromedriver.storage.googleapis.com/$CHROME_DRIVER_VERSION/chromedriver_linux64.zip
        unzip chromedriver_linux64.zip -d /usr/local/bin/
        rm chromedriver_linux64.zip
        pip install -r requirements.txt

    - name: Run update script
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        API_KEY: ${{ secrets.API_KEY }}
        SEARCH_ENGINE_ID: ${{ secrets.SEARCH_ENGINE_ID }}
        DISPLAY: :99
      run: |
        sudo Xvfb :99 -ac &
        python malagacalendar.py

