name: Update Google Calendar

on:
  schedule:
    - cron: '0 12 * * 6'  # Ejecutar todos los sábados a las 12:00 UTC
  workflow_dispatch:  # Permitir la ejecución manual

jobs:
  update-calendar:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write # Permiso para hacer push

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.4'

    - name: Install dependencies
      run: |
        # Actualizar e instalar dependencias del SO y Google Chrome
        sudo apt-get update
        sudo apt-get install -y wget xvfb libxi6 tzdata
        wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo dpkg -i google-chrome-stable_current_amd64.deb
        sudo apt-get -fy install
        rm google-chrome-stable_current_amd64.deb
        
        # Instalar dependencias de Python
        pip install -r requirements.txt

    - name: Run update script
      env:
        DISPLAY: :99
      run: |
        sudo Xvfb :99 -ac &
        python malagacalendar.py

    - name: Commit and push if changes
      run: |
        git config --global user.name "GitHub Action Bot"
        git config --global user.email "github-actions-bot@users.noreply.github.com"
        git add partidos.ics
        # Comprobar si hay cambios para commitear
        if git diff --staged --quiet; then
          echo "No hay cambios en el calendario, no se requiere commit."
        else
          git commit -m "Actualización automática de calendario 🤖"
          git push
        fi
