name: Selenium Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.4'

    - name: Install dependencies
      run: |
        sudo apt-get update
        # --- AQUÍ ESTÁ EL CAMBIO: Se ha quitado libgconf-2-4 ---
        sudo apt-get install -y wget unzip xvfb libxi6
        wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo dpkg -i google-chrome-stable_current_amd64.deb
        sudo apt-get -fy install
        CHROME_DRIVER_VERSION=`curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE`
        pip install -r requirements.txt

    - name: Run Selenium Tests
      env:
        # GOOGLE_APPLICATION_CREDENTIALS ya no es necesario
        DISPLAY: :99
      run: |
        sudo Xvfb :99 -ac &
        python malagacalendar.py
